### ISSUE TITLE
C++ API reference/documentation?

### ISSUE THREAD

**Issue by frantic0** [RMResearch/OpenMPD#3]
Hi @RobertoMontano @diegomp1982 

is there any C++ API reference/documentation available for OpenMPD? 

Thanks,
Francisco

**Comment by diegomp1982** [comment]
Hi!
The OpenMPD paper provides an introduction to the main concepts related to creating content with OpenMPD, as well as a high level description of the architecture. You can then get more detail from the [tutorial guide](https://github.com/RMResearch/OpenMPD/blob/main/Docs/OpenMPD%20Tutorial_Guide.pdf) 
The source code also contains comments to generate the Doxigen documentation. 
Hope that helps. 
Diego
